#!/bin/bash -ex

# Set variables
APP_VER=4.2.7
USER=mayan
APP_NAME=mayan-edms
APP_DIR=/opt/$APP_NAME
BIN=$APP_DIR/bin
DB_NAME=$USER
DB_USER=$USER
DB_PASS=$(mcookie)
RE_PASS=$(mcookie)
RMQ_PASS=$(mcookie)
SV_CONF=/etc/supervisor/conf.d/$USER.conf
ENV_CONF=/etc/$USER/env

adduser $USER --disabled-password --disabled-login --no-create-home --gecos ""

python3 -m venv /opt/mayan-edms
chown -R $USER:$USER $APP_DIR
mkdir -p /var/log/$USER
chown -R $USER:$USER /var/log/$USER

su - $USER -c "/opt/mayan-edms/bin/pip install pip==21.3.1"

# create convenience env dirs file
mkdir -p $(dirname $ENV_CONF)
cat > $ENV_CONF <<EOF
export MAYAN_DATABASES="{
    'default':{
        'ENGINE':'django.db.backends.postgresql',
        'NAME':'$DB_NAME',
        'PASSWORD':'$DB_PASS',
        'USER':'$DB_USER',
        'HOST':'127.0.0.1'
    }
}"
export MAYAN_CELERY_BROKER_URL="amqp://mayan:$RMQ_PASS@127.0.0.1:5672/mayan"
export MAYAN_CELERY_RESULT_BACKEND="redis://:$RE_PASS@127.0.0.1:6379/1"
export MAYAN_LOCK_MANAGER_BACKEND="mayan.apps.lock_manager.backends.redis_lock.RedisLock"
export MAYAN_LOCK_MANAGER_BACKEND_ARGUMENTS="{'redis_url':'redis://:$RE_PASS@127.0.0.1:6379/2'}"
export MAYAN_MEDIA_ROOT=$APP_DIR/media
EOF

RMQ_CONF=/etc/rabbitmq/rabbitmq-env.conf
sed -i 's/#NODENAME=.*/NODENAME=mayan@mayan-edms/' $RMQ_CONF
sed -i 's/#NODE_IP_ADDRESS/NODE_IP_ADDRESS/' $RMQ_CONF
sed -i 's/#NODE_PORT/NODE_PORT/' $RMQ_CONF

service postgresql start

# Install mayan (pretty much) as per "basic deployment" from the "direct
# deployments" docs: https://docs.mayan-edms.com/chapters/deploying.html

su - $USER -c "$BIN/pip install --no-cache-dir -U pip"
su - $USER -c "$BIN/pip install --no-cache-dir '$APP_NAME==$APP_VER'"
su - $USER -c "$BIN/pip install --no-cache-dir amqp==5.0.9 psycopg2==2.9.2 redis==4.0.2"

service rabbitmq-server start
rabbitmqctl add_user mayan ${RMQ_PASS};
rabbitmqctl add_vhost mayan;
rabbitmqctl set_permissions -p mayan mayan ".*" ".*" ".*"

# tweak redis
REDIS_CONF=/etc/redis/redis.conf
echo "maxmemory-policy allkeys-lru" >> $REDIS_CONF
echo "save \"\"" >> $REDIS_CONF
echo "databases 3" >> $REDIS_CONF
echo "requirepass $RE_PASS" >> $REDIS_CONF

service redis-server start


su - postgres -c "createuser $DB_USER"
su - postgres -c "createdb -O $DB_USER $DB_NAME"
su - postgres -c "psql postgres" <<EOF
alter user $DB_USER with encrypted password '$DB_PASS';
EOF

su - $USER -c ". $ENV_CONF && $BIN/mayan-edms.py initialsetup"
su - $USER -c ". $ENV_CONF && $BIN/mayan-edms.py platformtemplate supervisord" \
    > $SV_CONF

#su - $USER -c ". $ENV_CONF && $BIN/mayan-edms.py makemigrations"
#su - $USER -c ". $ENV_CONF && $BIN/mayan-edms.py performupgrade"
#su - $USER -c ". $ENV_CONF && $BIN/mayan-edms.py collectstatic --noinput"

sed -i 's|LOGGING_LOG_FILE_PATH: .*|LOGGING_LOG_FILE_PATH: /var/log/mayan/error.log|' $APP_DIR/media/config.yml
touch /var/log/mayan/error.log
chown mayan:mayan /var/log/mayan/error.log

# include mayan version in build log
installed_version=$(cat $APP_DIR/media/system/VERSION)

# update mayan admin password so "First time login" is never displayed
/usr/lib/inithooks/bin/mayan.py --email=admin@example.com --pass=$DB_PASS

service postgresql stop
service redis-server stop
rabbitmqctl stop

# nginx config
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/mayan /etc/nginx/sites-enabled/mayan
ln -s /etc/adminer/nginx.conf /etc/nginx/sites-available/adminer
ln -s /etc/nginx/sites-available/adminer /etc/nginx/sites-enabled/adminer

# Configure fastcgi for Adminer via Nginx (php-fastcgi)
systemctl enable php-fastcgi
