#!/bin/bash -e
# regenerate mayan pgsql password

. /etc/default/inithooks

MAYAN_CONF=/opt/mayan-edms/media/config.yml
RE_CONF=/etc/redis/redis.conf
RMQ_CONF=/etc/rabbitmq/rabbitmq-env.conf
ENV=/etc/mayan/env
DB_USER=mayan

# Create new passwords
DB_PASS=$(mcookie)
RE_PASS=$(mcookie)
RMQ_PASS=$(mcookie)

# Update DB password in Supervisor config, as well as env file
sed -iE '/^DATABASES/,/^[^ \t]/ s/PASSWORD:.*/PASSWORD: '$DB_PASS'/g' $MAYAN_CONF
sed -i "\|PASSWORD|s|:.*|:'$DB_PASS',|" $ENV

# Update the DB user password in postgres
$INITHOOKS_PATH/bin/pgsqlconf.py --user=$DB_USER --pass="$DB_PASS"

# regen the Django secret
#. /opt/mayan-edms/bin/activate
#python $INITHOOKS_PATH/bin/mayan-gen-secret.py
#deactivate

# Update Redis password
sed -i "s|redis://.*@|redis://:${RE_PASS}@|" $MAYAN_CONF
sed -i "\|^requirepass|s| .*| ${RE_PASS}|" $RE_CONF

service rabbitmq-server start
# Update RabbitMQ password
rabbitmqctl change_password mayan "${RMQ_PASS}"
sed -i "s|amqp.*@|amqp://mayan:${RMQ_PASS}@|" $MAYAN_CONF

# reload supervisor to ensure new db password is used
# we don't use `supervisor restart` here because it fails in chroot
service supervisor stop 
service supervisor start
service redis-server restart
service rabbitmq-server restart
